DrugName={'Fungal infection':'Clotrimazole','Allergy':'Pseudoephedrine','GERD':'lansoprazole','Chronic cholestasis':'Ursodeoxycholic acid',
          'Drug Reaction':'Corticosteroid','Peptic ulcer diseae':' lansoprazole','AIDS':'antiretroviral therapy','Diabetes':'Metformin',
          'Gastroenteritis':'bismuth subsalicylate','Bronchial Asthma':'albuterol','Hypertension':'Cardizem','Migraine':'promethazine hydrochloride',
          'Cervical spondylosis':'cyclobenzaprine','Paralysis (brain hemorrhage)':'Refer doctor','Jaundice':'phenobarbital','Malaria':'Mefloquine',
          'Chicken pox':'acyclovir','Dengue':'Acetaminophen','Typhoid':'Ceftriaxone','hepatitis A':'Havrix','Hepatitis B':'telbivudine',
          'Hepatitis C':'sofosbuvir','Hepatitis D':' pegylated interferon alfa','Hepatitis E':'cyclosporine','Alcoholic hepatitis':'pentoxifylline',
          'Tuberculosis':'rifampin','Common Cold':'Combiflame','Pneumonia':'Zithromax','Dimorphic hemmorhoids(piles)':'ProctoCream',
          'Heart attack':'Refer to doctor','Varicose veins':'sodium tetradecyl sulfate','Hypothyroidism':'levothyroxine','Hyperthyroidism':'Methimazole',
          'Hypoglycemia':'Sulfonylureas','Arthritis':'celecoxib','(vertigo) Paroymsal  Positional Vertigo':'Meclizine','Acne':'Tetracycline',
          'Urinary tract infection':'Fosfomyci','Psoriasis':'Adalimumab','Impetigo':'mupirocin','back Pain':'Codeine','itching':'Opcon-A','skin rash':'prednisone',
          'nodal skin eruptions':'prednisone','continuous sneezing':'Diphenhydramine','shivering':'Diphenhydramine','chills':'Diphenhydramine',
          'joint pain':'Codeine','stomach pain':'Baralgan','acidity':'Ocid','ulcers on tongue':'benzocaine','muscle wasting':'Zanaflex',
          'vomiting':'Ativan','burning micturition':'Ocid','spotting urination':'fosfomycin','fatigue':'Armodafinil',
          'weight gain':'Lorcaserin','anxiety':'Chlordiazepoxide','cold hands and feets':'Diphenhydramine','mood swings':'Risperidone',
          'weight loss':'Lorcaserin','restlessness':'Aripiprazole','lethargy':'modafinil','patches in throat':'Becasule',
          'irregular sugar level':'Insulin','cough':'Cheston Cold','fever':'paracetamol','sunken eyes':'Eyetone',
          'breathlessness':'Inhaler','sweating':' ','dehydration':'ORS','indigestion':'Metrogyl','headache':'Disprin',
          'yellowish skin':'Cordova','dark urine':'Pristiq','nausea':'Ativan','loss of appetite':'Metrogyl',
          'pain behind the eyes':'Eyetone','back pain':'Sprix','constipation':'Fiboro','abdominal pain':'Move',
          'diarrhoea':'Metrogyl','mild fever':'paracetamol','yellow urine':'modafinil','yellowing of eyes':'Eyetone',
          'acute liver failure':'acetylcysteine','swelling of stomach':'Tioconazole','swelled lymph nodes':'Tioconazole',
          'malaise':'Apremilast','blurred and distorted vision':'Eyetone','phlegm':'Corex','throat irritation':'Corex',
          'redness of eyes':'Eyetone','sinus pressure':'Strepsil','runny nose':'Cheston Cold','congestion':'Metrogyl',
          'chest pain':'Norfloxocyn','weakness in limbs':'Voliny','fast heart rate':'Mesotrocin',
          'pain during bowel movements':'Atedocrox','pain in anal region':'Atedocrox','bloody stool':'Atedocrox',
          'irritation in anus':'Atedocrox','neck pain':'fosfomycin','dizziness':'ORS','cramps':'Move','bruising':'Savlon',
          'obesity':'FatGo','swollen legs':'Sodium tablets','swollen blood vessels':'Sodium tablets',
          'puffy face and eyes':'Sodium tablets','enlarged thyroid':'Sodium tablets','brittle nails':'Sodium tablets',
          'swollen extremeties':'Sodium tablets','excessive hunger':'Mecardo','extra marital contacts':'Mecardo',
          'drying and tingling lips':'ORS','slurred speech':'Magnecium Tablets','knee pain':'Moove','hip joint pain':'Moove',
          'muscle weakness':'Moove','stiff neck':'Moove','swelling joints':'Moove','movement stiffness':'Moove',
          'spinning movements':'Moove','loss of balance':'Magnesium Tablets','unsteadiness':'Magnesium Tablets',
          'weakness of one body side':'Moove','loss of smell':'Strepsil','bladder discomfort':'Atedocrox',
          'foul smell of urine':'Atedocrox','continuous feel of urine':'Atedocrox','passage of gases':'Atedocrox',
          'internal itching':'Norfloxocin','toxic look (typhos)':'Tretinoin','depression':'Magnecium Tablets',
          'irritability':'Magnecium Tablets','muscle pain':'Moove','altered sensorium':'Moove',
          'red spots over body':'Clotrimazole','belly pain':'Metrogyl','abnormal menstruation':'Levonorgestrel',
          'dischromic  patches':'Clotrimazole','watering from eyes':'Eyetone','increased appetite':'Phentermine',
          'polyuria':'Varenicline','family history':' ','mucoid sputum':'Savlon','rusty sputum':'Savlon',
          'lack of concentration':'Magnesium Tablets','visual disturbances':'Magnesium Tablets',
          'receiving blood transfusion':'Valturna','receiving unsterile injections':'Septonol','coma':' ',
          'stomach bleeding':'Metrogyl','distention of abdomen':'Metrogyl','history of alcohol consumption':'Nicotine',
          'fluid overload':'Vyvanse','blood in sputum':'Savlon','prominent veins on calf':'Junel Fe 1 / 20',
          'palpitations':'Junel Fe 1 / 20','painful walking':'Moove','pus filled pimples':'Junel Fe 1 / 20',
          'blackheads':'Junel Fe 1 / 20','scurring':'Junel Fe 1 / 20','skin peeling':'Cetaphil',
          'silver like dusting':'Cetaphil','small dents in nails':'Candid','inflammatory nails':'Candid',
          'blister':'Candid','red sore around nose':'Candid','yellow crust ooze':'Candid'}